blenderblog/urls.py
from django.contrib import admin
from django.urls import include, path 

urlpatterns = [
    path('', include('staticpages.urls')), 
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
     path('', views.PostListView.as_view(), name='index'),
     path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
     path('create/', views.PostCreateView.as_view(), name='create'),
     path('delete/<int:pk>/', views.DeletePostView.as_view(), name='delete'),
     path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
     path('<int:post_id>/comment/', views.create_comment, name='comment'),
     path('categories/', views.CategoryListView.as_view(), name='categories'),
     path('categoryFilter/<int:pk>', views.CategoryFilterView.as_view(), name='categoryFilter')
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

posts/models.py
from django.db import models
from django.conf import settings

class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.CharField(max_length=10000)
    date = models.DateTimeField()
    thumb = models.CharField(max_length=255, blank=True)
    text1 = models.CharField(max_length=1000, blank=True)
    text2 = models.CharField(max_length=1000, blank=True)
    img2 = models.CharField(max_length=255, blank=True)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return f'{self.title} ({self.date})'
    
class Comment(models.Model):
    date = models.DateTimeField()
    text = models.CharField(max_length=1000)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    project = models.ForeignKey(Post, on_delete=models.CASCADE)

staticpages/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django.forms import ModelForm
from .models import Post, Comment,Category
from django import forms

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'text1',
            'thumb',
            'text2',
            'img2',
            'categories'
        ]
        labels = {
            'title':"Título",
            'text1':"Primeiro bloco de texto:",
            'thumb':"Link da primeira imagem:",
            'text2':"Segundo bloco de texto:",
            'img2':"Link da segunda imagem:",
            'categories': "Selecione uma ou mais categorias:"
        }

        

        widgets = {
            'text1': forms.Textarea(attrs={'rows': 4, 'cols': 50}), 
            'text2': forms.Textarea(attrs={'rows': 4, 'cols': 50}),
            'categories':  forms.CheckboxSelectMultiple()
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Escreva seu comentário',
        }
        widgets = {
            'text': forms.Textarea(attrs={'rows': 4, 'cols': 50})  
        }

posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment, Category
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .forms import CommentForm, PostForm
from django.views import generic
from datetime import datetime




class PostListView(generic.ListView):
    model = Post
    template_name = 'posts/index.html'

class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'posts/detail.html'
    

class PostCreateView(generic.CreateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/create.html'
    def form_valid(self, form):
        post = form.save(commit=False)
        post.date = datetime.now()
        post_thumb = form.cleaned_data['thumb']
        post_image = form.cleaned_data['img2']
        post_text1 = form.cleaned_data['text1']
        post_text2 = form.cleaned_data['text2']
        post.content = f'<section class="ProjectContent"><p class="ProjectText">{post_text1}</p><img class="ProjectImage" src="{post_thumb}" title="source: imgur.com" /><p class="ProjectText">{post_text2}</p><img  class="ProjectImage" src="{post_image}" title="source: imgur.com" /></section>'
        post.text1 = post_text1
        post.text2 = post_text2
        post.img2 = post_image
        post.save()
        post.categories.set(form.cleaned_data['categories'])

        return HttpResponseRedirect(reverse('posts:detail', args=(post.id,)))

class DeletePostView(generic.DeleteView):
    model = Post
    template_name = 'posts/delete.html'
    success_url = reverse_lazy("posts:index")

class PostUpdateView(generic.UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/update.html'
    success_url = reverse_lazy('posts:detail')

    def form_valid(self, form):
        post = form.instance
        post_title = form.cleaned_data['title']
        post_thumb = form.cleaned_data['thumb']
        post_image = form.cleaned_data['img2']
        post_text1 = form.cleaned_data['text1']
        post_text2 = form.cleaned_data['text2']
        post.title = post_title
        post.date = datetime.now()
        post.thumb = post_thumb
        post.content = '<section class="ProjectContent"><p class="ProjectText">' + post_text1 + '</p><img class="ProjectImage" src="'+post_thumb+'" title="source: imgur.com" /><p class="ProjectText">' + post_text2 + '</p><img class="ProjectImage" src="'+post_image+'" title="source: imgur.com" /></section>'
        post.text1 = post_text1
        post.text2 = post_text2
        post.img2 = post_image
        post.categories.set(form.cleaned_data['categories'])
        post.save()
        return HttpResponseRedirect(
                reverse('posts:detail', args=(post.id, )))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = self.object
        return context

def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            project=post, 
                            date = datetime.now())
            comment.save()
            return HttpResponseRedirect(
                reverse('posts:detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post':post}
    return render(request, 'posts/comment.html', context)


class CategoryListView(generic.ListView):
    model = Category
    template_name = 'posts/categories/categories.html'

class CategoryFilterView(generic.DetailView):
    model = Category
    template_name = 'posts/categories/categoryFilter.html'

staticpages/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)

def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

# Create your views here.

posts/templates/posts/categories/categories.html
{% extends 'base.html' %}
{% load static %}


{%block style %}
<link rel="stylesheet" type="text/css" href="{% static 'global.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'list.css' %}">
{% endblock style %}

{% block content %}
<h2>Categorias</h2>


{% if category_list %}
    {% for category in category_list %}
        <li>
        <div style="background-color: rgb(233, 233, 233); margin: 32px;padding-bottom: 8px; border-radius: 0.5rem;">
            <a style="margin: 32px;" class="projectName" href="{% url 'posts:categoryFilter' category.id  %}">{{ category.name }}</a>
            <p style="margin-left: 64px; margin-bottom: 16px;">{{category.description}}</p>
        </div>
        </li>
    {% endfor %}
    
</ul>
{% else %}<p>Nenhuma categoria encontrada.</p>
{% endif %}


{% endblock content %}

posts/templates/posts/categories/categoryFilter.html
{% extends 'base.html' %}
{% load static %}


{%block style %}
<link rel="stylesheet" type="text/css" href="{% static 'global.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'list.css' %}">
{% endblock style %}

{% block content %}
<h2>Projetos da categoria "{{category.name}}"</h2>


{% if category.post_set.all %}
<ul class="projectsShowcase">
    {% for post in category.post_set.all %}
        <li><div class="projectCard">
            <img class="projectImage" src={{post.thumb}}>
            <a class="projectName" href="{% url 'posts:detail' post.id  %}">{{ post.title }}</a>
        </div></li>
    {% endfor %}
    
</ul>
{% else %}<p style="margin: 64px;">Nenhum projeto dessa categoria encontrado no sistema.</p>
{% endif %}


{% endblock content %}

posts/templates/posts/comment.html
{% extends 'base.html' %}
{% load static %} 

{%block style %}
<link rel="stylesheet" type="text/css" href="{% static 'global.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'single.css' %}">
{% endblock style %}

{% block content %}
<h2>Comentar no projeto {{ post.title }} </h2>

<div class="postForm">
<form action="{% url 'posts:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="postButton" type="submit"><p>Criar</p></button>
</form>
</div>

<div class="postForm">
<p><a class="buttonText" href="{% url 'posts:detail' post.id %}">Voltar para a página do projeto</a></p>
</div>
{% endblock content %}

posts/templates/posts/create.html
{% extends 'base.html' %}
{% load static %} 

{%block style %}
<link rel="stylesheet" type="text/css" href="{% static 'global.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'single.css' %}">
{% endblock style %}

{% block content %}
<h2>Postar um novo projeto</h2>

<div class="postForm">
<form method="POST" action="{% url 'posts:create' %}">
  {% csrf_token %}
  {{ form.as_p }}
    <button class="postButton" type="submit"><p>Criar</p></button>
  </form>
</div>
  
  {% endblock content %}

posts/templates/posts/delete.html
{% extends 'base.html' %}
{% load static %}

{%block style %}
<link rel="stylesheet" type="text/css" href="{% static 'global.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'single.css' %}">
{% endblock style %}

{% block content %}
<form action="{% url 'posts:delete' post.id %}" method="post">
  {% csrf_token %}
  <h2>
    Você tem certeza que deseja apagar o projeto "{{ post.title }}"?
  </h2>
  <p style="padding: 16px 32px;">Essa ação é definitiva e apaga todo o conteúdo do post e seus comentários.</p>
  <button class="postButton" type="submit"><p>Apagar</p></button>
</form>
{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}
{% load static %} 

{%block style %}
<link rel="stylesheet" type="text/css" href="{% static 'global.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'single.css' %}">
{% endblock style %}

{% block content %}
<h2>{{post.title}}</h2>
{% if post.categories.all %}
    <ul style="display: flex; justify-content: left; align-items: center;">
    <li><p style="margin-left:64px; font-size: 22px;">Categorias:</p></li>
    {% for category in post.categories.all%}
    <li class="postButton" style="width: 4rem; height: 0.5rem; margin: 8px 16px;">
        <a style="font-size: 18px;" class="buttonText" href="{% url 'posts:categoryFilter' category.id  %}">{{ category.name }}</a></li>
    
    {% endfor%}
    </ul>
{%endif%}
<div style="display: flex; flex-direction: row;">
<div class="postButton">
    <a class="buttonText" href="{% url 'posts:delete' post.id %}">🗑️ Apagar o projeto</a>
</div>
<div class="postButton">
    <a class="buttonText" href="{% url 'posts:update' post.id %}">✏️ Editar o projeto</a>
</div>
</div>


{{post.content|safe}}

<h2>Comentários</h2>
<div class="postButton">
    <a class="buttonText" href="{% url 'posts:comment' post.pk %}">💬 Comentar</a>
</div>
<ul style="display: flex; flex-direction: column; padding: 0 80px;">
    {% if post.comment_set.all %}
        {% for comment in post.comment_set.all|dictsortreversed:"date" %}
            <div style="padding: 16px;">
                <p>
                    "{{ comment.text }}"
                </p>
                <p style="padding: 0 16px; color: rgb(121, 121, 121);">—{{ comment.author }}  -  {{comment.date|date:"d/m/Y, H:i"}}</p>
            </div>
        {% endfor %}
    {% else %}
        <p>Não há comentários no post deste projeto.</p>
    {% endif %}
</ul>

{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}


{%block style %}
<link rel="stylesheet" type="text/css" href="{% static 'global.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'list.css' %}">
{% endblock style %}

{% block content %}
<h2>Projetos</h2>
<div class="postButton">
    <a class="projectName" href="{% url 'posts:create' %}">     ➕ Postar um novo projeto!</a>
</div>

{% if post_list %}
<ul class="projectsShowcase">
    {% for post in post_list %}
        <li><div class="projectCard">
            <img class="projectImage" src={{post.thumb}}>
            <a class="projectName" href="{% url 'posts:detail' post.id  %}">{{ post.title }}</a>
        </div></li>
    {% endfor %}
    
</ul>
{% else %}<p>Nenhum projeto foi encontrado no sistema.</p>
{% endif %}


{% endblock content %}

posts/templates/posts/update.html
{% extends 'base.html' %}
{% load static %} 

{%block style %}
<link rel="stylesheet" type="text/css" href="{% static 'global.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'single.css' %}">
{% endblock style %}

{% block content %}
<h2>Editar o projeto:  {{post.title}}</h2>

<div class="postForm">
<form method="POST" action="{% url 'posts:update' post.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="postButton" type="submit"><p>Salvar edição</p></button>
  </form>
</div>
  
  {% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}
{% load static %}

{%block style %}
<link rel="stylesheet" type="text/css" href="{% static 'global.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'single.css' %}">
{% endblock style %}

{% block title %}
Sobre mim
{% endblock title %}


{% block content %}
<div class="aboutMe">
    <img id="myPhoto" src="{% static '/images/foto.jpg' %}" />
    <p id="aboutMeText">Prazer! Meu nome é Matheus Latorre Cavini, tenho 20 anos e moro na cidade de Santo André - SP. Sou estudante de engenharia mecatrônica na Escola Politécnica da USP. Tenho como hobby o audiovisual, principalmente na área relacionada a CGI. Tive meu primeiro contato com o Blender durante a pandemia, em 2020, e desde então tenho buscado desenvolver alguns projetos nas horas vagas.</p>
</div>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}
{% load static %}

{%block style %}
<link rel="stylesheet" type="text/css" href="{% static 'global.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
{% endblock style %}

{% block title %}
Home
{% endblock title %}

{% block content %}
<div>
    <img src="{% static '/images/Lightsaber_Home.png' %}" width="100%" />
    <h1 id="HomeTitle">Bem-vindo ao meu portfólio!</h1>
</div class="HomeContent">
<h2 id="HomeSubtitle">Conheça meus projetos como artista amador no software Blender</h2>
<section class="HomeSection" >
    <img src="{% static '/images/sorvete_Home.png' %}" class="HomeImg"/>
    <p class="HomeText">Aprendi a utilizar o Blender seguindo tutoriais no YouTube. Conforme fui ganhando prática, comecei a tentar algumas experimentações por conta própria.  </p>
</section>
<section class="HomeSection" >
    <p class="HomeText">Inspirados principalmente em filmes e séries, meus projetos tem enfoque em modelagem e texturização. Gosto de produzir renders finais que saltem aos olhos. </p>
    <img src="{% static '/images/Arc_reactor_Home.png' %}" class="HomeImg"/>
</section>
<section class="HomeSection" >
    <img src="{% static '/images/abb_Home.png' %}" class="HomeImg"/>
    <p class="HomeText">Às vezes também me sobra um tempo para mistrurar meu hobby com minha graduação... </p>
</section><section class="HomeSection" >
    <p class="HomeText">... ou com minha banda favorita. </p>
    <img src="{% static '/images/TOP_Home.png' %}" class="HomeImg"/>
</section>
<h2 id="HomeFoot">Visite a aba "Projetos" para conhecer mais</h2>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800&display=swap" rel="stylesheet">
    {% block style %}{%endblock style %}

    <title>{% block title %}{% endblock %}</title>

</head>

<body>
    <header>
        <div id="title"><img src="{% static '/images/logo.png' %}" height="80">
            <h1>Portfólio Blender - Matheus Cavini</h1>
            <nav>
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'posts:index' %}">Projetos</a></li>
                <li><a href="{% url 'posts:categories' %}">Categorias</a></li>
                <li><a href="{% url 'about' %}">Sobre mim</a></li>
                
            </ul>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
    <footer>
        <ul id="contactsMedia">
            <li class="mediaItem"><img src="{% static '/images/email.png' %}" height="28px"/><p class="media">matheuslcavini@usp.br</p></li>
            <li class="mediaItem"><img src="{% static '/images/ig.png' %}" height="28px"/><p class="media">@matheus_cavini</p></li>
            <li class="mediaItem"><img src="{% static '/images/fb.png' %}" height="28px"/><p class="media">Matheus Cavini</p></li>
    
        </ul>
        <p id="Copyright">Copyright 2023 -  Matheus Cavini</p>
    </footer>

</body>
</html>